//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Control_asistencia_mvc
{
    using System;
    using System.Collections.Generic;
    
    public partial class empleados
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public empleados()
        {
            this.control_asistencia = new HashSet<control_asistencia>();
        }
    
        public long id_empl { get; set; }
        public string nombres { get; set; }
        public string apelli { get; set; }
        public Nullable<int> id_cargo { get; set; }
        public Nullable<int> id_depto { get; set; }
        public Nullable<System.DateTime> fecha_ingreso { get; set; }
        public Nullable<int> id_tipo_empl { get; set; }
    
        public virtual cargos cargos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<control_asistencia> control_asistencia { get; set; }
        public virtual departamentos departamentos { get; set; }
        public virtual tipo_empleado tipo_empleado { get; set; }
    }
}
